name: Run Makefile and execute output

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Makefile
        run: make -C Esercizi/exercise1

      - name: Execute output and check result
        run: |
          ./Esercizi/exercise1/main
          result=$?
          output="Test terminated with $result error"
          if [ "$result" -ne 1 ]; then
            output+="s"
          fi
          echo output
          if [ "$result" -ne 0 ]; then
            echo "Test failed! Please check the code before pushing again."
            exit 1
          fi
