name: Run Makefile and execute output

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Install specific version of g++
        run: |
          sudo apt-get install -y g++-13.2.0
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13.2.0 60

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout other repo into zmytest
        uses: actions/checkout@v4
        with:
          repository: 'RiccardoElena/LASD_test'
          path: 'Esercizi/exercise1/zmytest'
          token: ${{ secrets.PAT }}

      - name: Checkout other repo into zmytest
        uses: actions/checkout@v4
        with:
          repository: 'RiccardoElena/LASD_test'
          path: 'Esercizi/exercise2/zmytest'
          token: ${{ secrets.PAT }}

      - name: Run Makefile
        run: ./.github/workflows/scripts/compile.sh

      - name: Execute output and check result
        run: ./.github/workflows/scripts/run.sh
