name: Run Makefile and execute output

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Makefile
        run: make

      - name: Execute output and check result
        run: |
          result=$(./main)
          echo "Test terminated with $result error(s)"
          if [ "$result" -ne 0 ]; then
            echo "Test failed! Please check the code before pushing again."
            exit 1
          fi
