name: Run Makefile and execute output

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Checkout other repo into zmytest
      #  uses: actions/checkout@v4
      #  with:
      #    repository: 'RiccardoElena/LASD_test'
      #    path: 'Esercizi/exercise2/zmytest'
      #    token: ${{ secrets.PAT }}

      - name: Install g++-13
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install g++-13 -y

      - name: Set g++ version to 13
        run: |
          sudo apt-get remove g++-11 -y
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: Run Makefile
        run: ./.github/workflows/scripts/compile.sh

      - name: Check times
        run: ./.github/workflows/scripts/time.sh 200

      - name: Execute output and check result
        run: ./.github/workflows/scripts/run.sh
